
class MissionAlgor(db.Model):
    #LEMIid
    #ALGOid
    MIALid = db.Column(db.String(36), nullable=False, primary_key=True)
    LEMIid = db.Column(db.String(36), ForeignKey('learnMission.LEMIid')
    ALGOid = db.Column(db.String(36), ForeignKey('algorithm.ALGOid')
    code = db.Column(db.String(30), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    type = db.Column(db.SMALLINT, nullable=False)
    sequence = db.Column(db.INTEGER, nullable=False)
    #primary key (MIALid)


class MissionPar(db.Model):
#MIALid
    MIPAid = db.Column(db.String(36), nullable=False, primary_key=True)
    MIALid = db.Column(db.String(36), ForeignKey('MissionAlgor.MIALid')
    code = db.Column(db.String(50), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    value = db.Column(db.String(100), nullable=False)
    illustration = db.Column(db.String(200), nullable=False, default=' ')
    #primary key (MIPAid)


class accessory(db.Model):
    ACCEid = db.Column(db.String(36), nullable=False, primary_key=True)
    ownerid = db.Column(db.String(36), nullable=False)
    realFilename = db.Column(db.String(100), nullable=False, default=' ')
    filename = db.Column(db.String(100), nullable=False, default=' ')
    filetype = db.Column(db.String(50), nullable=False, default=' ')
    path = db.Column(db.String(200), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    #primary key (ACCEid)


class algorithm(db.Model):
    ALGOid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(30), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    type = db.Column(db.SMALLINT, nullable=False)
    illustration = db.Column(db.String(300), nullable=False, default=' ')
    #primary key (ALGOid)


class algorithmPar(db.Model):
#ALGOid
    ALPAid = db.Column(db.String(36), nullable=False, primary_key=True)
    ALGOid = db.Column(db.String(36), ForeignKey('algorithm.ALGOid')
    code = db.Column(db.String(50), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    value = db.Column(db.String(100), nullable=False)
    illustration = db.Column(db.String(200), nullable=False, default=' ')
    #primary key (ALPAid)


class ancientBook(db.Model):
#REBOid
    ANBOid = db.Column(db.String(36), nullable=False, primary_key=True)
    REBOid = db.Column(db.String(36), ForeignKey('readBook.REBOid')
    literature_name = db.Column(db.String(20), nullable=False, default=' ')
    pubType = db.Column(db.String(10), nullable=False, default=' ')
    benefit = db.Column(db.String(100), nullable=False, default=' ')
    #primary key (ANBOid)


class ancientSpecialist(db.Model):
#REBOid
    ANSPid = db.Column(db.String(36), nullable=False, primary_key=True)
    REBOid = db.Column(db.String(36), ForeignKey('readBook.REBOid')
    name = db.Column(db.String(20), nullable=False)
    major = db.Column(db.String(100), nullable=False)
    #primary key (ANSPid)


class background(db.Model):
#STSTid
    BACKid = db.Column(db.String(36), nullable=False, primary_key=True)
    STSTid = db.Column(db.String(36), ForeignKey('studyStory.STSTid')
    sport = db.Column(db.String(300), nullable=False)
    literature = db.Column(db.String(300), nullable=False)
    health = db.Column(db.String(300), nullable=False)
    tour = db.Column(db.String(300), nullable=False)
    other_hobby = db.Column(db.String(300), nullable=False)
    smoke = db.Column(db.String(300), nullable=False)
    coffee = db.Column(db.String(300), nullable=False)
    alcohol = db.Column(db.String(300), nullable=False)
    tea = db.Column(db.String(300), nullable=False)
    movie = db.Column(db.String(300), nullable=False)
    other_habit = db.Column(db.String(300), nullable=False)
    chinese = db.Column(db.String(300), nullable=False)
    philosophy = db.Column(db.String(300), nullable=False)
    art = db.Column(db.String(300), nullable=False)
    custom = db.Column(db.String(300), nullable=False)
    belief = db.Column(db.String(300), nullable=False)
    other_culture = db.Column(db.String(300), nullable=False)
    other_experience = db.Column(db.Text, nullable=False, default=' ')
    tiptop_duty = db.Column(db.String(300), nullable=False)
    years = db.Column(db.String(10), nullable=False)
    organization = db.Column(db.String(300), nullable=False)
    parttime_duty = db.Column(db.String(300), nullable=False)
    glory = db.Column(db.String(300), nullable=False)
    acquire_time = db.Column(db.String(10), nullable=False)
    #primary key (BACKid)


class badInstance(db.Model):
#REBOid
    BAINid = db.Column(db.String(36), nullable=False, primary_key=True)
    REBOid = db.Column(db.String(36), ForeignKey('readBook.REBOid')
    content = db.Column(db.Text, nullable=False, default=' ')
    #primary key (BAINid)


class basicinformation(db.Model):
#SpecialisId
    Num = db.Column(db.String(50), nullable=False)
    Name = db.Column(db.String(50), nullable=False)
    Gender = db.Column(db.String(50), nullable=False)
    Age = db.Column(db.String(50), nullable=False)
    Diploma = db.Column(db.String(50), nullable=False)
    Dgree = db.Column(db.String(50), nullable=False)
    Rank = db.Column(db.String(50))
    PromotionTime = db.Column(db.String(50))
    Duty = db.Column(db.Text)
    HashId = db.Column(db.String(36), nullable=False, primary_key=True)
    State = db.Column(db.SMALLINT)
    SpecialisId = db.Column(db.String(36), ForeignKey('specialist.SPETid')
    OperatorId = db.Column(db.String(36))
    CreateDate = db.Column(db.DateTime)
    #primary key (HashId)


class bookResult(db.Model):
#SpecialistId
    Num = db.Column(db.String(50))
    Title = db.Column(db.String(50))
    Author = db.Column(db.String(50))
    AuthorAffiliation = db.Column(db.String(50))
    Abstract = db.Column(db.Text)
    Source = db.Column(db.String(50))
    Files = db.Column(db.String(50))
    SpecialistId = db.Column(db.String(36), ForeignKey('specialist.SPETid')
    OperatorId = db.Column(db.String(36))
    HashId = db.Column(db.String(36), nullable=False, primary_key=True)
    State = db.Column(db.SMALLINT)
    #primary key (HashId)


class cDisease(db.Model):
    CDISid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(100), nullable=False)
    parentcode = db.Column(db.String(20), nullable=False)
    level = db.Column(db.SMALLINT, nullable=False)
    isClassical = db.Column(db.Boolean, nullable=False, default=1)
    SPETid = db.Column(db.String(36), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (CDISid)
    #key AK_CDISEASE_PK_CODE_CDISEASE (code)


class caseAnalysis(db.Model):
    #SPETid
    CAANid = db.Column(db.String(36), nullable=False, primary_key=True)
    SPETid = db.Column(db.String(36), ForeignKey('specialist.SPETid')
    CASEid = db.Column(db.String(36), nullable=False)
    diagnose_mode = db.Column(db.SMALLINT, nullable=False, default=0)
    diagnose_method = db.Column(db.SMALLINT, nullable=False, default=0)
    look_body = db.Column(db.String(50), nullable=False)
    illustration = db.Column(db.Text, nullable=False)
    tongue = db.Column(db.SMALLINT, nullable=False, default=0)
    tongue1 = db.Column(db.String(50), nullable=False)
    look_place = db.Column(db.String(50), nullable=False)
    sound = db.Column(db.String(50), nullable=False)
    taste = db.Column(db.String(50), nullable=False)
    question_answer = db.Column(db.String(200), nullable=False)
    question_content = db.Column(db.Text, nullable=False)
    special_question = db.Column(db.String(200), nullable=False)
    feel_diagnose = db.Column(db.String(200), nullable=False)
    habit_dmethod = db.Column(db.String(200), nullable=False)
    important_question = db.Column(db.String(500), nullable=False)
    information_select = db.Column(db.String(200), nullable=False)
    analysis_way = db.Column(db.String(500), nullable=False)
    analysis_method = db.Column(db.SMALLINT, nullable=False, default=0)
    other_method = db.Column(db.String(200), nullable=False)
    analysis_evidence = db.Column(db.String(200), nullable=False)
    reason_evidence = db.Column(db.String(200), nullable=False)
    character_evidence = db.Column(db.String(200), nullable=False)
    place_evidence = db.Column(db.String(200), nullable=False)
    situation_evidence = db.Column(db.String(200), nullable=False)
    semiotics = db.Column(db.String(50), nullable=False)
    recipe_name = db.Column(db.String(50), nullable=False)
    produce_method = db.Column(db.String(200), nullable=False)
    takedrug_way = db.Column(db.String(200), nullable=False)
    doctor_advice = db.Column(db.Text, nullable=False)
    experience = db.Column(db.String(500), nullable=False)
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (CAANid)


class classicCase(db.Model):
#SPETid
    clcaid = db.Column(db.String(36), nullable=False, primary_key=True)
    operatorId = db.Column(db.String(36))
    SPETid = db.Column(db.String(36), ForeignKey('specialist.SPETid')
    state = db.Column(db.SMALLINT)
    diagnosisNo = db.Column(db.String(50))
    creatDate = db.Column(db.DateTime)
    num = db.Column(db.String(36), nullable=False)
    title = db.Column(db.String(50))
    source = db.Column(db.SMALLINT)
    caseNum = db.Column(db.String(50))
    name = db.Column(db.String(50))
    gender = db.Column(db.String(50))
    birthday = db.Column(db.String(50))
    people = db.Column(db.String(50))
    job = db.Column(db.String(50))
    hometown = db.Column(db.String(50))
    married = db.Column(db.String(50))
    address = db.Column(db.String(50))
    postcode = db.Column(db.String(50))
    phone = db.Column(db.String(50))
    presentIll = db.Column(db.Text)
    pastIll = db.Column(db.Text)
    familyIll = db.Column(db.Text)
    personalIll = db.Column(db.Text)
    visit = db.Column(db.Text)
    note = db.Column(db.Text)
    remark = db.Column(db.Text)
    collectPerson = db.Column(db.String(50))
    collectTime = db.Column(db.String(50))
    verifyOpinion = db.Column(db.Text)
    verifyName = db.Column(db.String(50))
    verifyTime = db.Column(db.String(50))
    diagTime1 = db.Column(db.String(50))
    mainDisease1 = db.Column(db.Text)
    caseAbstract1 = db.Column(db.Text)
    zhengKeys1 = db.Column(db.Text)
    westdisease1 = db.Column(db.String(50))
    tcmdisease1 = db.Column(db.String(50))
    tcmsyndrome1 = db.Column(db.String(50))
    therapy1 = db.Column(db.Text)
    fangYao1 = db.Column(db.Text)
    otherCure1 = db.Column(db.Text)
    doctorAdvice1 = db.Column(db.Text)
    efficacy1 = db.Column(db.String(50))
    diagTime2 = db.Column(db.String(50))
    mainDisease2 = db.Column(db.Text)
    caseAbstract2 = db.Column(db.Text)
    zhengKeys2 = db.Column(db.Text)
    westdisease2 = db.Column(db.String(50))
    tcmdisease2 = db.Column(db.String(50))
    tcmsyndrome2 = db.Column(db.String(50))
    therapy2 = db.Column(db.Text)
    fangYao2 = db.Column(db.Text)
    otherCure2 = db.Column(db.Text)
    doctorAdvice2 = db.Column(db.Text)
    efficacy2 = db.Column(db.String(50))
    diagTime3 = db.Column(db.String(50))
    mainDisease3 = db.Column(db.Text)
    caseAbstract3 = db.Column(db.Text)
    zhengKeys3 = db.Column(db.Text)
    westdisease3 = db.Column(db.String(50))
    tcmdisease3 = db.Column(db.String(50))
    tcmsyndrome3 = db.Column(db.String(50))
    therapy3 = db.Column(db.Text)
    fangYao3 = db.Column(db.Text)
    otherCure3 = db.Column(db.Text)
    doctorAdvice3 = db.Column(db.Text)
    efficacy3 = db.Column(db.String(50))
    diagTime4 = db.Column(db.String(50))
    mainDisease4 = db.Column(db.Text)
    caseAbstract4 = db.Column(db.Text)
    zhengKeys4 = db.Column(db.Text)
    westdisease4 = db.Column(db.String(50))
    tcmdisease4 = db.Column(db.String(50))
    tcmsyndrome4 = db.Column(db.String(50))
    therapy4 = db.Column(db.Text)
    fangYao4 = db.Column(db.Text)
    otherCure4 = db.Column(db.Text)
    doctorAdvice4 = db.Column(db.Text)
    efficacy4 = db.Column(db.String(50))
    diagTime5 = db.Column(db.String(50))
    mainDisease5 = db.Column(db.Text)
    caseAbstract5 = db.Column(db.Text)
    zhengKeys5 = db.Column(db.Text)
    westdisease5 = db.Column(db.String(50))
    tcmdisease5 = db.Column(db.String(50))
    tcmsyndrome5 = db.Column(db.String(50))
    therapy5 = db.Column(db.Text)
    fangYao5 = db.Column(db.Text)
    otherCure5 = db.Column(db.Text)
    doctorAdvice5 = db.Column(db.Text)
    efficacy5 = db.Column(db.String(50))
    diagTime6 = db.Column(db.String(50))
    mainDisease6 = db.Column(db.Text)
    caseAbstract6 = db.Column(db.Text)
    zhengKeys6 = db.Column(db.Text)
    westdisease6 = db.Column(db.String(50))
    tcmdisease6 = db.Column(db.String(50))
    tcmsyndrome6 = db.Column(db.String(50))
    therapy6 = db.Column(db.Text)
    fangYao6 = db.Column(db.Text)
    otherCure6 = db.Column(db.Text)
    doctorAdvice6 = db.Column(db.Text)
    efficacy6 = db.Column(db.String(50))
    diagTime7 = db.Column(db.String(50))
    mainDisease7 = db.Column(db.Text)
    caseAbstract7 = db.Column(db.Text)
    zhengKeys7 = db.Column(db.Text)
    westdisease7 = db.Column(db.String(50))
    tcmdisease7 = db.Column(db.String(50))
    tcmsyndrome7 = db.Column(db.String(50))
    therapy7 = db.Column(db.Text)
    fangYao7 = db.Column(db.Text)
    otherCure7 = db.Column(db.Text)
    doctorAdvice7 = db.Column(db.Text)
    efficacy7 = db.Column(db.String(50))
    diagTime8 = db.Column(db.String(50))
    mainDisease8 = db.Column(db.Text)
    caseAbstract8 = db.Column(db.Text)
    zhengKeys8 = db.Column(db.Text)
    westdisease8 = db.Column(db.String(50))
    tcmdisease8 = db.Column(db.String(50))
    tcmsyndrome8 = db.Column(db.String(50))
    therapy8 = db.Column(db.Text)
    fangYao8 = db.Column(db.Text)
    otherCure8 = db.Column(db.Text)
    doctorAdvice8 = db.Column(db.Text)
    efficacy8 = db.Column(db.String(50))
    diagTime9 = db.Column(db.String(50))
    mainDisease9 = db.Column(db.Text)
    caseAbstract9 = db.Column(db.Text)
    zhengKeys9 = db.Column(db.Text)
    westdisease9 = db.Column(db.String(50))
    tcmdisease9 = db.Column(db.String(50))
    tcmsyndrome9 = db.Column(db.String(50))
    therapy9 = db.Column(db.Text)
    fangYao9 = db.Column(db.Text)
    otherCure9 = db.Column(db.Text)
    doctorAdvice9 = db.Column(db.Text)
    efficacy9 = db.Column(db.String(50))
    diagTime10 = db.Column(db.String(50))
    mainDisease10 = db.Column(db.Text)
    caseAbstract10 = db.Column(db.Text)
    zhengKeys10 = db.Column(db.Text)
    westdisease10 = db.Column(db.String(50))
    tcmdisease10 = db.Column(db.String(50))
    tcmsyndrome10 = db.Column(db.String(50))
    therapy10 = db.Column(db.Text)
    fangYao10 = db.Column(db.Text)
    otherCure10 = db.Column(db.Text)
    doctorAdvice10 = db.Column(db.Text)
    efficacy10 = db.Column(db.String(50))
    diagTime11 = db.Column(db.String(50))
    mainDisease11 = db.Column(db.Text)
    caseAbstract11 = db.Column(db.Text)
    zhengKeys11 = db.Column(db.Text)
    westdisease11 = db.Column(db.String(50))
    tcmdisease11 = db.Column(db.String(50))
    tcmsyndrome11 = db.Column(db.String(50))
    therapy11 = db.Column(db.Text)
    fangYao11 = db.Column(db.Text)
    otherCure11 = db.Column(db.Text)
    doctorAdvice11 = db.Column(db.Text)
    efficacy11 = db.Column(db.String(50))
    diagTime12 = db.Column(db.String(50))
    mainDisease12 = db.Column(db.Text)
    caseAbstract12 = db.Column(db.Text)
    zhengKeys12 = db.Column(db.Text)
    westdisease12 = db.Column(db.String(50))
    tcmdisease12 = db.Column(db.String(50))
    tcmsyndrome12 = db.Column(db.String(50))
    therapy12 = db.Column(db.Text)
    fangYao12 = db.Column(db.Text)
    otherCure12 = db.Column(db.Text)
    doctorAdvice12 = db.Column(db.Text)
    efficacy12 = db.Column(db.String(50))
    diagTime13 = db.Column(db.String(50))
    mainDisease13 = db.Column(db.Text)
    caseAbstract13 = db.Column(db.Text)
    zhengKeys13 = db.Column(db.Text)
    westdisease13 = db.Column(db.String(50))
    tcmdisease13 = db.Column(db.String(50))
    tcmsyndrome13 = db.Column(db.String(50))
    therapy13 = db.Column(db.Text)
    fangYao13 = db.Column(db.Text)
    otherCure13 = db.Column(db.Text)
    doctorAdvice13 = db.Column(db.Text)
    efficacy13 = db.Column(db.String(50))
    diagTime14 = db.Column(db.String(50))
    mainDisease14 = db.Column(db.Text)
    caseAbstract14 = db.Column(db.Text)
    zhengKeys14 = db.Column(db.Text)
    westdisease14 = db.Column(db.String(50))
    tcmdisease14 = db.Column(db.String(50))
    tcmsyndrome14 = db.Column(db.String(50))
    therapy14 = db.Column(db.Text)
    fangYao14 = db.Column(db.Text)
    otherCure14 = db.Column(db.Text)
    doctorAdvice14 = db.Column(db.Text)
    efficacy14 = db.Column(db.String(50))
    diagTime15 = db.Column(db.String(50))
    mainDisease15 = db.Column(db.Text)
    caseAbstract15 = db.Column(db.Text)
    zhengKeys15 = db.Column(db.Text)
    westdisease15 = db.Column(db.String(50))
    tcmdisease15 = db.Column(db.String(50))
    tcmsyndrome15 = db.Column(db.String(50))
    therapy15 = db.Column(db.Text)
    fangYao15 = db.Column(db.Text)
    otherCure15 = db.Column(db.Text)
    doctorAdvice15 = db.Column(db.Text)
    efficacy15 = db.Column(db.String(50))
    diagTime16 = db.Column(db.String(50))
    mainDisease16 = db.Column(db.Text)
    caseAbstract16 = db.Column(db.Text)
    zhengKeys16 = db.Column(db.Text)
    westdisease16 = db.Column(db.String(50))
    tcmdisease16 = db.Column(db.String(50))
    tcmsyndrome16 = db.Column(db.String(50))
    therapy16 = db.Column(db.Text)
    fangYao16 = db.Column(db.Text)
    otherCure16 = db.Column(db.Text)
    doctorAdvice16 = db.Column(db.Text)
    efficacy16 = db.Column(db.String(50))
    diagTime17 = db.Column(db.String(50))
    mainDisease17 = db.Column(db.Text)
    caseAbstract17 = db.Column(db.Text)
    zhengKeys17 = db.Column(db.Text)
    westdisease17 = db.Column(db.String(50))
    tcmdisease17 = db.Column(db.String(50))
    tcmsyndrome17 = db.Column(db.String(50))
    therapy17 = db.Column(db.Text)
    fangYao17 = db.Column(db.Text)
    otherCure17 = db.Column(db.Text)
    doctorAdvice17 = db.Column(db.Text)
    efficacy17 = db.Column(db.String(50))
    diagTime18 = db.Column(db.String(50))
    mainDisease18 = db.Column(db.Text)
    caseAbstract18 = db.Column(db.Text)
    zhengKeys18 = db.Column(db.Text)
    westdisease18 = db.Column(db.String(50))
    tcmdisease18 = db.Column(db.String(50))
    tcmsyndrome18 = db.Column(db.String(50))
    therapy18 = db.Column(db.Text)
    fangYao18 = db.Column(db.Text)
    otherCure18 = db.Column(db.Text)
    doctorAdvice18 = db.Column(db.Text)
    efficacy18 = db.Column(db.String(50))
    #primary key (clcaid)


class classicCaseDiagnosis(db.Model):
    clcaid = db.Column(db.String(36), nullable=False, primary_key=True)
    caseNum = db.Column(db.String(50))
    diagnosisNum = db.Column(db.String(50))
    diagTime = db.Column(db.String(50))
    mainDisease = db.Column(db.Text)
    caseAbstract = db.Column(db.Text)
    zhengKeys = db.Column(db.Text)
    westdisease = db.Column(db.String(50))
    tcmdisease = db.Column(db.String(50))
    tcmsyndrome = db.Column(db.String(50))
    therapy = db.Column(db.Text)
    fangYao = db.Column(db.Text)
    otherCure = db.Column(db.Text)
    doctorAdvice = db.Column(db.Text)
    efficacy = db.Column(db.String(50))
    #primary key (clcaid)


class continuingeducation(db.Model):
    #SpecialisId
    Participent = db.Column(db.String(50))
    TrainingName = db.Column(db.String(50))
    Category = db.Column(db.String(50))
    TrainingDate = db.Column(db.String(50))
    Hours = db.Column(db.String(50))
    CreditHour = db.Column(db.String(50))
    HashId = db.Column(db.String(36), nullable=False, primary_key=True)
    SpecialisId = db.Column(db.String(36), ForeignKey('specialist.SPETid')
    State = db.Column(db.SMALLINT)
    OperatorId = db.Column(db.String(36))
    CreateDate = db.Column(db.DateTime)
    #primary key (HashId)


class dCase(db.Model):
    CASEid = db.Column(db.String(36), nullable=False, primary_key=True)
    SPETid = db.Column(db.String(36), nullable=False, default=' ')
    DTMPid = db.Column(db.String(36), nullable=False, default=' ')
    code = db.Column(db.String(20), nullable=False)
    outpatientCode = db.Column(db.String(20), nullable=False)
    caseKind = db.Column(db.SMALLINT, nullable=False)
    name = db.Column(db.String(20), nullable=False)
    age = db.Column(db.SMALLINT, nullable=False)
    month = db.Column(db.SMALLINT, nullable=False, default=0)
    gender = db.Column(db.SMALLINT, nullable=False)
    nationality = db.Column(db.SMALLINT, nullable=False)
    personSort = db.Column(db.SMALLINT, nullable=False)
    afflication = db.Column(db.String(200), nullable=False, default=' ')
    job = db.Column(db.String(20), nullable=False, default=' ')
    tel = db.Column(db.String(20), nullable=False, default=' ')
    address = db.Column(db.String(200), nullable=False, default=' ')
    birthplace = db.Column(db.String(6), nullable=False)
    liveplace = db.Column(db.String(6), nullable=False)
    education = db.Column(db.SMALLINT, nullable=False)
    marriage = db.Column(db.SMALLINT, nullable=False)
    ohistory = db.Column(db.Text, nullable=False, default=' ')
    phistory = db.Column(db.Text, nullable=False, default=' ')
    fhistory = db.Column(db.Text, nullable=False, default=' ')
    allergy = db.Column(db.Text, nullable=False, default=' ')
    extraMed = db.Column(db.String(500), nullable=False, default=' ')
    nhistory = db.Column(db.Text, nullable=False, default=' ')
    mresult = db.Column(db.SMALLINT, nullable=False)
    vresult = db.Column(db.String(500), nullable=False)
    illustration = db.Column(db.Text, nullable=False, default=' ')
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    hasFile = db.Column(db.Boolean, nullable=False, default=0)
    preState = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (CASEid)
    #check = db.Column(db.([age] >= 0 and [age] <= 999)


class dMethod(db.Model):
    DMETid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(100), nullable=False)
    parentcode = db.Column(db.String(20), nullable=False)
    level = db.Column(db.SMALLINT, nullable=False)
    isClassical = db.Column(db.Boolean, nullable=False, default=1)
    SPETid = db.Column(db.String(36), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (DMETid)
    #key AK_DMETHOD_PK_CODE_DMETHOD (code)


class dTemplate(db.Model):
    DTMPid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(200), nullable=False)
    useClassCdis = db.Column(db.Boolean, nullable=False, default=0)
    useClassDmet = db.Column(db.Boolean, nullable=False, default=0)
    CDISid = db.Column(db.String(36), nullable=False, default=' ')
    WDISid = db.Column(db.String(36), nullable=False, default=' ')
    SEMCid = db.Column(db.String(36), nullable=False)
    DMETid = db.Column(db.String(36), nullable=False)
    takeWay = db.Column(db.SMALLINT, nullable=False)
    drugForm = db.Column(db.SMALLINT, nullable=False)
    SPETid = db.Column(db.String(36), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    useClassWdis = db.Column(db.Boolean, nullable=False, default=0)
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (DTMPid)
    #key AK_DTEMPLATE_PK_CODE_DTEMPLAT (code)


class dataSet(db.Model):
    DASEid = db.Column(db.String(36), nullable=False, primary_key=True)
    DTMPid = db.Column(db.String(36), nullable=False)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    missionType = db.Column(db.SMALLINT, nullable=False)
    sampleNum = db.Column(db.INTEGER, nullable=False, default=0)
    attributeNum = db.Column(db.INTEGER, nullable=False, default=0)
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    #primary key (DASEid)


class diagExam(db.Model):
    #EXAMid
    #DIAGid
    DIEXid = db.Column(db.String(36), nullable=False, primary_key=True)
    DIAGid = db.Column(db.String(36), ForeignKey('diagnose.DIAGid')
    EXAMid = db.Column(db.String(36), ForeignKey('examination.EXAMid')
    value = db.Column(db.String(200), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    date = db.Column(db.DateTime)
    sequence = db.Column(db.INTEGER, default=0)
    address = db.Column(db.String(100))
    #primary key (DIEXid)


class diagItem(db.Model):
#dru_DRUGid
#DIREid
    DIITid = db.Column(db.String(36), nullable=False, primary_key=True)
    DIREid = db.Column(db.String(36), ForeignKey('diagRecipe.DIREid')
    dru_DRUGid = db.Column(db.String(36), ForeignKey('drug.DRUGid')
    DRUGid = db.Column(db.String(36))
    quality = db.Column(db.DECIMAL(18,4), nullable=False, default=0)
    sequence = db.Column(db.INTEGER, nullable=False, default=0)
    illustration = db.Column(db.Text, nullable=False, default=' ')
    #primary key (DIITid)


class diagRecipe(db.Model):
    #FREPid
    #DIAGid
    DIREid = db.Column(db.String(36), nullable=False, primary_key=True)
    DIAGid = db.Column(db.String(36), ForeignKey('diagnose.DIAGid')
    FREPid = db.Column(db.String(36), ForeignKey('fixedrecipe.FREPid')
    isCustomed = db.Column(db.Boolean, nullable=False, default=0)
    name = db.Column(db.String(36), nullable=False, default=' ')
    doctorAdvice = db.Column(db.Text, nullable=False, default=' ')
    drugForm = db.Column(db.SMALLINT, nullable=False)
    takeWay = db.Column(db.SMALLINT, nullable=False)
    quality = db.Column(db.SMALLINT, nullable=False)
    produceMethod = db.Column(db.String(100), nullable=False)
    usage = db.Column(db.String(100), nullable=False)
    #primary key (DIREid)


class diagSymptom(db.Model):
#SYPMid
#DIAGid
    DISYid = db.Column(db.String(36), nullable=False, primary_key=True)
    SYPMid = db.Column(db.String(36), ForeignKey('symptom.SYPMid')
    DIAGid = db.Column(db.String(36), ForeignKey('diagnose.DIAGid')
    value = db.Column(db.String(200), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    sequence = db.Column(db.INTEGER, default=0)
    #primary key (DISYid)


class diagnose(db.Model):
    #CASEid
    DIAGid = db.Column(db.String(36), nullable=False, primary_key=True)
    CASEid = db.Column(db.String(36), ForeignKey('dCase.CASEid')
    CDISid = db.Column(db.String(36), nullable=False, default=' ')
    CDISid2 = db.Column(db.String(36), nullable=False, default=' ')
    WDISid = db.Column(db.String(36), nullable=False, default=' ')
    WDISid2 = db.Column(db.String(36), nullable=False, default=' ')
    SEMCid = db.Column(db.String(36), nullable=False)
    SEMCid2 = db.Column(db.String(36), nullable=False)
    SEMCid3 = db.Column(db.String(36), nullable=False)
    DMETid = db.Column(db.String(36), nullable=False)
    DMETid2 = db.Column(db.String(36), nullable=False)
    DMETid3 = db.Column(db.String(36), nullable=False)
    DIAGno = db.Column(db.SMALLINT, nullable=False, default=1)
    DIAGnum = db.Column(db.SMALLINT, nullable=False)
    DIAGday = db.Column(db.DateTime, nullable=False)
    lunarDay = db.Column(db.String(50), nullable=False, default=' ')
    solarTerm = db.Column(db.SMALLINT, nullable=False, default=0)
    DIAway = db.Column(db.SMALLINT, nullable=False, default=0)
    majorSue = db.Column(db.Text, nullable=False)
    illustration = db.Column(db.Text, nullable=False, default=' ')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    westernMed = db.Column(db.Text, nullable=False, default=' ')
    other = db.Column(db.Text, nullable=False, default=' ')
    preSEMCid = db.Column(db.String(36))
    #primary key (DIAGid)


class district(db.Model):
    DISTid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    parentcode = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    level = db.Column(db.SMALLINT, nullable=False)
    py = db.Column(db.String(20), nullable=False, default=' ')
    wb = db.Column(db.String(20), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    #primary key (DISTid)
    #key AK_DISTRICT_PK_CODE_DISTRICT (code)


class drug(db.Model):
    DRUGid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    unit = db.Column(db.String(10), nullable=False)
    alias = db.Column(db.String(100), nullable=False, default=' ')
    py = db.Column(db.String(20), nullable=False, default=' ')
    wb = db.Column(db.String(20), nullable=False, default=' ')
    isClassical = db.Column(db.Boolean, nullable=False, default=1)
    SPETid = db.Column(db.String(36), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (DRUGid)
    #key AK_DRUG_PK_CODE_DRUG (code)


class dtmpExamination(db.Model):
    #EXAMid
    #DTMPid
    DTEXid = db.Column(db.String(36), nullable=False, primary_key=True)
    DTMPid = db.Column(db.String(36), ForeignKey('dTemplate.DTMPid')
    EXAMid = db.Column(db.String(36), ForeignKey('examination.EXAMid')
    sequence = db.Column(db.INTEGER, nullable=False)
    illustration = db.Column(db.Text, nullable=False)
    #primary key (DTEXid)


class dtmpSymptom(db.Model):
    #SYPMid
    #DTMPid
    DTSYid = db.Column(db.String(36), nullable=False, primary_key=True)
    DTMPid = db.Column(db.String(36), ForeignKey('dTemplate.DTMPid')
    SYPMid = db.Column(db.String(36), ForeignKey('symptom.SYPMid')
    isFirst = db.Column(db.Boolean, nullable=False, default=1)
    sequence = db.Column(db.INTEGER, nullable=False, default=0)
    illustration = db.Column(db.Text, nullable=False, default=' ')
    #primary key (DTSYid)


class examination(db.Model):
    EXAMid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(100), nullable=False)
    abbreviation = db.Column(db.String(50), nullable=False, default=' ')
    kind = db.Column(db.SMALLINT, nullable=False, default=0)
    normalValue = db.Column(db.String(200), nullable=False, default=' ')
    hasFile = db.Column(db.Boolean, nullable=False, default=0)
    isClassical = db.Column(db.Boolean, nullable=False, default=1)
    SPETid = db.Column(db.String(36), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (EXAMid)
    #key AK_EXAMINATION_PK_COD_EXAMINAT (code)


class feature(db.Model):
#DASEid
    FEATid = db.Column(db.String(36), nullable=False, primary_key=True)
    DASEid = db.Column(db.String(36), ForeignKey('dataSet.DASEid')
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    featType = db.Column(db.SMALLINT, nullable=False)
    valSort = db.Column(db.SMALLINT, nullable=False, default=0)
    sequence = db.Column(db.INTEGER, nullable=False)
    #primary key (FEATid)


class fileinfo(db.Model):
    FIlEINFOid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    SPETid = db.Column(db.String(36), nullable=False)
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False)
    optrid = db.Column(db.String(36), nullable=False)
    state = db.Column(db.SMALLINT, nullable=False)
    fileinfoType = db.Column(db.SMALLINT, nullable=False)
    #primary key (FIlEINFOid)


class fixedrecipe(db.Model):
    FREPid = db.Column(db.String(36), nullable=False, primary_key=True)
    code = db.Column(db.String(20), nullable=False)
    name = db.Column(db.String(50), nullable=False)
    effect = db.Column(db.String(200), nullable=False, default=' ')
    py = db.Column(db.String(20), nullable=False, default=' ')
    wb = db.Column(db.String(20), nullable=False, default=' ')
    isClassical = db.Column(db.Boolean, nullable=False, default=1)
    SPETid = db.Column(db.String(36), nullable=False, default=' ')
    illustration = db.Column(db.Text, nullable=False, default=' ')
    createDay = db.Column(db.DateTime, nullable=False, default='1900-1-1')
    optrid = db.Column(db.String(36), nullable=False, default=' ')
    state = db.Column(db.SMALLINT, nullable=False, default=0)
    #primary key (FREPid)
    #key AK_FIXEDRECIPE_PK_COD_FIXEDREC (code)


class fixedrecipeItem(db.Model):
#FREPid
#DRUGid
    FRITid = db.Column(db.String(36), nullable=False, primary_key=True)
    DRUGid = db.Column(db.String(36), ForeignKey('drug.DRUGid')
    FREPid = db.Column(db.String(36), ForeignKey('fixedrecipe.FREPid')
    quality = db.Column(db.DECIMAL(18,4), nullable=False, default=0)
    sequence = db.Column(db.INTEGER, nullable=False, default=0)
    illustration = db.Column(db.Text, nullable=False, default=' ')
    #primary key (FRITid)


